# JPA
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${host}:${port}/${dbname}"
    username: ${username}
    password: ${password}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  lifecycle:
    shutdown:
      timeout-per-shutdown-phase: 20s
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

aws:
  ses:
    send-mail-to: ${AWS_SEND_MAIL_TO}
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}

domain:
  url: ${DOMAIN_URL}

cors:
  allowed-origins: ${ALLOWED_ORIGINS}

server:
  url: ${SERVER_URL}
  shutdown: graceful



