version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: past-forward
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: past-forward
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: dev
      MYSQL_PASSWORD: 1234
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    restart: always
    image: redis:alpine
    container_name: past-forward-redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - "6380:6379"

volumes:
  data:

