version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: past-forward
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: past-forward
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: dev
      MYSQL_PASSWORD: 1234
      volumes: data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  data:

